spring.application.name=notification
server.port=8083


#Conexao com o sistema de ms_perfil sincrono
app.services.perfil.url=http://localhost:8082

spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
medcare.aws.sqs.queue.notification.email=NotificationEmailQueue

# ----------------------------------------
# 4. Configuracao do MySQL (ms_notification)
# ----------------------------------------
 spring.datasource.url=jdbc:mysql://localhost:3306/ms_notification
 spring.datasource.username=root
 spring.datasource.password=admin
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # Configuracoes do JPA/Hibernate
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ----------------------------------------
# 5. Configuração da Conexão H2 (URL, Driver, Dialect)
# ----------------------------------------

# Tipo de conexão: in-memory (dados perdidos ao reiniciar)
#spring.datasource.url=jdbc:h2:mem:testdb
# Nome de usuário e senha (opcional para in-memory, mas bom para prática)
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.datasource.driverClassName=org.h2.Driver

# Habilita o Hibernate a usar o dialeto H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ----------------------------------------
# 6. Configuração da Inicialização e Console
# ----------------------------------------

# Habilita o console do H2 (Interface Web para visualizar os dados)
#spring.h2.console.enabled=true

# Define o caminho de acesso ao console (ex: http://localhost:8082/h2-console)
#spring.h2.console.path=/h2-console

# ------------------------------------------
# Configuracoes do email
# ------------------------------------------
broker.queue.email.name=default.email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucasem456@gmail.com
spring.mail.password=cdjs theo ykpc aeia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true